name = "zuri-oasis-elite"
compatibility_date = "2024-01-01"

[build]
command = "npm run build:frontend"

[assets]
directory = "frontend/build"

[env.production]
name = "zuri-oasis-elite"

[[env.production.routes]]
pattern = "zurioasiselite.icu/*"
zone_name = "zurioasiselite.icu"
